# Generated by Django 3.0.5 on 2021-04-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
