# Generated by Django 3.0.5 on 2021-04-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0002_auto_20210422_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
